INSERT INTO users (username, password) VALUES
                                                 ('admin','$2a$10$8uw8jFarRy51Ym4dcNpFLOj8miYfUUQjYIy/qgeWkCDxkwF9g0lbm'),
                                                 ('jane_doe', 'password123'),
                                                 ('event_coordinator', 'ec_pass'),
                                                 ('library_staff', 'ls_pass'),
                                                 ('campus_security','cs_pass'),
                                                 ('hr_manager','hm_pass'),
                                                 ('facilities_team','ft_pass'),
                                                 ('it_department','it_pass'),
                                                 ('city_clerk','cc_pass'),
                                                 ('transport_dept','td_pass'),
                                                 ( 'utility_board', 'utility_pass'),
                                                 ( 'mall_manager', 'mall_pass'),
                                                 ( 'marketing_team','mt_pass'),
                                                 ( 'hoa_admin', 'hoa_pass'),
                                                 ( 'maintenance_team', 'mt_pass'),
                                                 ( 'site_supervisor', 'ss_pass'),
                                                 ( 'safety_officer', 'so_pass'),
                                                 ( 'project_manager', 'pm_pass');

INSERT INTO user_roles (user_id, roles) VALUES
                                        (1, 'ADMIN'),
                                        (2, 'USER'),
                                        (3, 'USER'),
                                        (4, 'USER'),
                                        (5, 'USER'),
                                        (6, 'USER'),
                                        (7, 'USER'),
                                        (8, 'USER'),
                                        (9, 'USER'),
                                        (10, 'USER'),
                                        (11, 'USER'),
                                        (12, 'USER'),
                                        (13, 'USER'),
                                        (14, 'USER'),
                                        (15, 'USER'),
                                        (16, 'USER'),
                                        (17, 'USER'),
                                        (18, 'USER');

INSERT INTO announcement (title, content, start_date, end_date, published, owner_id) VALUES
                                                                                                  ('Road Closure Notice', 'Main Street will be closed for maintenance. Expect delays and follow detour signs.', '2025-01-15T00:00:00', '2025-12-20T00:00:00', true, 1),
                                                                                                  ( 'Community Cleanup Day', 'Join us for our annual cleanup event. Volunteers will meet at City Park at 9 AM.', '2025-02-05T00:00:00', '2025-12-06T00:00:00', true, 1),
                                                                                                  ( 'New Library Hours', 'The public library is extending its weekend hours starting next month.', '2025-03-01T00:00:00', '2025-12-31T00:00:00', true, 3),
                                                                                                  ( 'Water Service Interruption', 'Water supply will be temporarily unavailable due to pipe repairs in the downtown area.', '2025-01-25T00:00:00', '2025-12-26T00:00:00', true, 1),
                                                                                                  ( 'Holiday Event', 'Come celebrate with us at the annual Winter Festival with music, food, and fun activities.', '2025-11-01T00:00:00', '2025-12-31T00:00:00', true, 2),
                                                                                                  ( 'Exam Week Schedule', 'Final exams will take place from March 10–15. Check the student portal for room assignments.', '2025-03-01T00:00:00', '2025-12-15T00:00:00', true, 1),
                                                                                                  ( 'Campus Safety Drill', 'A mandatory evacuation drill will occur on February 20 at 11 AM. All students must participate.', '2025-02-10T00:00:00', '2025-12-20T00:00:00', true, 4),
                                                                                                  ( 'Library System Upgrade', 'Online library services will be unavailable on April 5 due to maintenance.', '2025-04-01T00:00:00', '2025-12-05T00:00:00', false, 3),
                                                                                                  ( 'Quarterly Town Hall Meeting', 'Join the leadership team for updates on company performance and goals.', '2025-01-20T00:00:00', '2025-12-22T00:00:00', true, 5),
                                                                                                  ( 'Office Renovation', 'Renovation of the 3rd floor begins February 10. Expect minor noise during work hours.', '2025-02-01T00:00:00', '2025-12-28T00:00:00', true, 6),
                                                                                                  ( 'Cybersecurity Training', 'All employees must complete the new cybersecurity training module by March 30.', '2025-03-01T00:00:00', '2025-12-30T00:00:00', true, 7),
                                                                                                  ( 'Public Hearing on Zoning Changes', 'Residents are invited to attend the zoning policy meeting at City Hall.', '2025-02-15T00:00:00', '2025-12-18T00:00:00', true, 8),
                                                                                                  ( 'Road Maintenance Update', 'Pine Avenue will be resurfaced from March 5–12. Expect temporary road closures.', '2025-03-01T00:00:00', '2025-03-12T00:00:00', true, 9),
                                                                                                  ( 'Utility Outage Notice', 'A planned power outage will affect the Elm District on January 30.', '2025-01-25T00:00:00', '2025-01-30T00:00:00', false, 10),
                                                                                                  ( 'Grand Opening: TechZone', 'A new electronics store, TechZone, opens on February 14 with exclusive discounts.', '2025-02-01T00:00:00', '2025-02-14T00:00:00', true, 11),
                                                                                                  ( 'Parking Garage Maintenance', 'Level 2 of the parking garage will be closed for cleaning on March 8.', '2025-03-05T00:00:00', '2025-12-08T00:00:00', true, 11),
                                                                                                  ( 'Spring Fashion Sale', 'Select stores will offer up to 50% off during the Spring Fashion Sale.', '2025-04-01T00:00:00', '2025-12-15T00:00:00', true, 12),
                                                                                                  ( 'Pool Closure for Repairs', 'The community pool will be closed from February 25 to March 3 for tile replacement.', '2025-02-20T00:00:00', '2025-03-03T00:00:00', true, 13),
                                                                                                  ( 'Fire Alarm Testing', 'Routine fire alarm testing will take place on April 10 from 9 AM to 12 PM.', '2025-04-01T00:00:00', '2025-04-10T00:00:00', true, 14),
                                                                                                  ( 'Spring Community BBQ', 'Residents are invited to a neighborhood BBQ on May 5 at the clubhouse.', '2025-04-15T00:00:00', '2025-12-05T00:00:00', false, 13),
                                                                                                  ( 'Crane Operation Alert', 'A crane will be operating onsite on March 18. Only authorized personnel are permitted near the south loading zone.', '2025-03-10T00:00:00', '2025-03-18T00:00:00', true, 15),
                                                                                                  ( 'Safety Gear Update', 'All workers must switch to the new-issued safety helmets starting April 1.', '2025-03-20T00:00:00', '2025-12-01T00:00:00', true, 16),
                                                                                                  ( 'Concrete Pouring Schedule', 'Concrete will be poured on the foundation from February 12–14. Expect restricted access.', '2025-02-01T00:00:00', '2025-12-14T00:00:00', false, 17),
                                                                                                  ( 'System Maintenance', 'The public portal will be offline for updates on February 28.', '2025-02-20T00:00:00', '2025-12-28T00:00:00', true, 17),
                                                                                                  ( 'Holiday Greetings', 'Wishing everyone a safe and happy holiday season!', '2025-12-01T00:00:00', '2025-12-31T00:00:00', true, 17);

INSERT INTO topics (name) VALUES
                                  ( 'Events'),
                                  ('Maintenance'),
                                  ( 'Safety'),
                                  ('Education'),
                                  ('Government'),
                                  ('Community'),
                                  ('Utilities'),
                                  ('Sales'),
                                  ('Construction'),
                                  ('Holiday');

INSERT INTO announcement_topics (announcement_id, topic_id) VALUES
                                                                (1,6),
                                                                (1,2),
                                                                (1,3),
                                                                (2,1),
                                                                (2,6),
                                                                (3,5),
                                                                (4,7),
                                                                (5,10),
                                                                (6,4),
                                                                (7,3),
                                                                (8,4),
                                                                (9,1),
                                                                (10,9),
                                                                (11,4),
                                                                (12,5),
                                                                (13,9),
                                                                (14,7),
                                                                (15,8),
                                                                (16,2),
                                                                (17,1),
                                                                (18,6),
                                                                (19,3),
                                                                (20,1),
                                                                (21,2),
                                                                (22,3),
                                                                (23,9),
                                                                (24,4),
                                                                (25,10);

